const Config = {
  recomputeNormals: false,
  reRig: false,
  isLockRotationY: false,
  isLockRotationX: false,
  model: {
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scale: 1,
  },
  selectedCamera: 0,
  cameras: [
    {
      distance: 3.01,
      height: 0.95,
      offsetX: 0,
      pitch: 0,
      rotationY: 0,
      fov: 26.9,
      eye: { position: {}, target: {}, up: {} },
    },
    {
      distance: 3.01,
      height: 0.95,
      offsetX: 0,
      pitch: 0,
      rotationY: 45,
      fov: 26.9,
      eye: { position: {}, target: {}, up: {} },
    },
    {
      distance: 3.01,
      height: 0.95,
      offsetX: 0,
      pitch: 0,
      rotationY: -45,
      fov: 26.9,
      eye: { position: {}, target: {}, up: {} },
    },
    {
      distance: 3.01,
      height: 0.95,
      offsetX: 0,
      pitch: 0,
      rotationY: 180,
      fov: 26.9,
      eye: { position: {}, target: {}, up: {} },
    },
  ],
  sun: {
    altitude: 1,
    eastWest: 0.2,
    intensity: 0.8,
    alpha: 1,
  },
  clear: {
    color: 0x3d4d4d,
    alpha: 1,
  },
  depthNear: 2.5,
  depthFar: 3,
  needsReload: false,
  keyframe: -1,
  pointSize: 3,
  labelScale: 1,
  showLabels: true,
  showPoints: true,
  showSkeleton: false,
  showJointLabels: false,
};
export default Config;
