const Config = {
  isZAxisUp: false,
  recomputeNormals: false,
  isLockRotationY: false,
  isLockRotationX: false,
  modelRotationTheta: 0,
  modelRotationPhi: 0,
  modelScale: 1,
  cameraDistance: 3,
  cameraHeight: 1.35,
  cameraPitch: -7,
  cameraRotationY: 0,
  cameraFOV: 26.9,
  needsReload: false,
  keyframe: -1,
  backgroundColor: 0x3d4d4d,
  pointSize: 3,
  labelScale: 1,
  showLabels: true,
  showPoints: true,
};
export default Config;
